### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Discostu36** [sjsone/vscode-neos-fusion-lsp#6]
The extension doesn't work for me and I don't know why. I don't get any hover information etc. 

Windows 11
Visual Studio Code 1.81.1
Neos Fusion & AFX Language Server 0.2.10 (I also tested with 0.3.1 but it made no difference)

**Comment by sjsone** [comment]
Thank you for raising the issue!

I tested it on my Windows 10 machine on both extension versions and unfortunately cannot reproduce the error. 

So it is either the Project, a local problem or Windows 11 (which is the least likely option).

Maybe there are some Error-Logs in the "Output" Tab next to the Terminal: 
<img width="1284" alt="Screenshot 2023-08-22 at 14 14 48" src="https://github.com/sjsone/vscode-neos-fusion-lsp/assets/87149727/594f2e0d-1420-49d5-9f3b-1e531445ea08">

I would advise to raise the Log-Level to **Verbose** or **Debug** in _Settings_ > _Extensions_ > _"NEOS Fusion & AFX Language Server"_ > Logging as well: 
<img width="862" alt="Screenshot 2023-08-22 at 14 07 32" src="https://github.com/sjsone/vscode-neos-fusion-lsp/assets/87149727/1bf0f8d7-7d9b-4b78-a3d4-e3303ae82dc7">

Then you should see something in the _Output_ you can paste here.

**Comment by Discostu36** [comment]
Thank you for your prompt reply. Here's a (pseudonymised) excerpt from the log:
````
[VERBOSE] <2023-08-23T08:45:10.666Z> [LanguageServer] Document opened: /neos/DistributionPackages/Demo.Site/Resources/Private/Fusion/Content/HinweisText.fusion
[VERBOSE] <2023-08-23T08:45:10.666Z> [LanguageServer] Document changed: /neos/DistributionPackages/Demo.Site/Resources/Private/Fusion/Content/HinweisText.fusion
[  DEBUG] <2023-08-23T08:45:10.674Z> [DocumentSymbolCapability] Could not find File for URI: file:///c%3A/Users/myUser/Desktop/Arbeitsordner/p3b/neos/DistributionPackages/Demo.Site/Resources/Private/Fusion/Content/HinweisText.fusion
[  DEBUG] <2023-08-23T08:45:10.693Z> [SemanticTokensLanguageFeature]  file:///c%3A/Users/myUser/Desktop/Arbeitsordner/p3b/neos/DistributionPackages/Demo.Site/Resources/Private/Fusion/Content/HinweisText.fusion
[  DEBUG] <2023-08-23T08:45:10.719Z> [InlayHintLanguageFeature]  file:///c%3A/Users/myUser/Desktop/Arbeitsordner/p3b/neos/DistributionPackages/Demo.Site/Resources/Private/Fusion/Content/HinweisText.fusion
[  DEBUG] <2023-08-23T08:45:11.052Z> [CodeLensCapability] Could not find File for URI: file:///c%3A/Users/myUser/Desktop/Arbeitsordner/p3b/neos/DistributionPackages/Demo.Site/Resources/Private/Fusion/Content/HinweisText.fusion
[  DEBUG] <2023-08-23T08:45:11.224Z> [InlayHintLanguageFeature]  file:///c%3A/Users/myUser/Desktop/Arbeitsordner/p3b/neos/DistributionPackages/Demo.Site/Resources/Private/Fusion/Content/HinweisText.fusion
[  DEBUG] <2023-08-23T08:45:13.309Z> [HoverCapability] Could not find File for URI: file:///c%3A/Users/myUser/Desktop/Arbeitsordner/p3b/neos/DistributionPackages/Demo.Site/Resources/Private/Fusion/Content/HinweisText.fusion
````

**Comment by sjsone** [comment]
Mhh i cannot see anything special about the file URIs compared to my logs. 

Does VSCode correctly opens a file if you CTRL-Click on one of the file URIs?
Which VSCode version do you use (including NodeJS version etc.) ?

**Comment by Discostu36** [comment]
Here are the first lines of the log when opening the workspace:

````
[   INFO] <2023-08-24T07:08:48.594Z> [LanguageServer] Added FusionWorkspace p3b with path c:\Users\myUser\Desktop\Arbeitsordner\p3b
[VERBOSE] <2023-08-24T07:08:48.832Z> [LanguageServer] Configuration: {"folders":{"packages":["DistributionPackages","Packages/Application","Packages/Framework","Packages/Plugins","Packages/Sites","Packages/Neos","Packages/Carbon"],"workspaceAsPackageFallback":true,"fusion":["Resources/Private/Fusion","Resources/Private/FusionModule","Resources/Private/FusionModules","Resources/Private/FusionPlugins","NodeTypes"],"ignore":["Packages/Libraries"],"followSymbolicLinks":false,"includeHiddenDirectories":false},"diagnostics":{"enabled":true,"ignoreNodeTypes":["Neos.Neos:Plugin"],"levels":{"deprecations":"hint"},"ignore":{"folders":["Packages/"]},"alwaysDiagnoseChangedFile":false},"inlayHint":{"depth":"literal"},"extensions":{"modify":true},"code":{"deprecations":{"fusion":{"prototypes":{"Neos.Fusion:Array":"Neos.Fusion:Join","Neos.Fusion:Collection":"Neos.Fusion:Loop","Neos.Fusion:RawCollection":"Neos.Fusion:Map","Neos.Fusion:RawArray":"Neos.Fusion:DataStructure","Neos.Fusion:UriBuilder":"Neos.Fusion:ActionUri"}}},"actions":{"createNodeTypeConfiguration":{"template":"{nodeTypeName}:\n  properties:"}}},"logging":{"level":"debug","inspect":false}}
File not found! c:\Users\myUser\Desktop\Arbeitsordner\p3b
[   INFO] <2023-08-24T07:08:48.834Z> [FusionWorkspace|p3b] Successfully parsed 0 fusion files. 
[  DEBUG] <2023-08-24T07:08:48.834Z> [FusionWorkspace|p3b] <62> Will diagnose 0 files
[  DEBUG] <2023-08-24T07:08:48.835Z> [FusionWorkspace|p3b] <62>...finished
[  DEBUG] <2023-08-24T07:08:48.913Z> [InlayHintLanguageFeature]  file:///c%3A/Users/myUser/Desktop/Arbeitsordner/p3b/neos/DistributionPackages/Demo.Site/Resources/Private/Fusion/Content/HinweisListe.fusion
[  DEBUG] <2023-08-24T07:08:49.673Z> [CodeLensCapability] Could not find File for URI: file:///c%3A/Users/myUser/Desktop/Arbeitsordner/p3b/neos/DistributionPackages/Demo.Site/Resources/Private/Fusion/Content/HinweisListe.fusion
````

When I CTRL+click on the link in the log, VS Code opens the file and the error message is repeated.

Version:
````
Version: 1.81.1 (user setup)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Datum: 2023-08-09T22:22:42.175Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
Betriebssystem: Windows_NT x64 10.0.22621
````

**Comment by sjsone** [comment]
The VSCode versions look good and the fact that the URI _should_ work is also a good sign. 

I have packaged a version with a bit more error output: 
[vscode-neos-fusion-lsp-0.3.7.vsix.zip](https://github.com/sjsone/vscode-neos-fusion-lsp/files/12443632/vscode-neos-fusion-lsp-0.3.7.vsix.zip)

The `.vsix` file can be installed in the context menu of the extensions tab: 

<img width="262" alt="Screenshot 2023-08-25 at 23 32 52" src="https://github.com/sjsone/vscode-neos-fusion-lsp/assets/87149727/c2162ccf-4df3-4e7c-a163-1381df8cfb07">

In the logs should now be the exact Error that gets thrown as well as the URI and file path. The later gets used to read in all the files so maybe thats not a valid path somehow.

**Comment by Discostu36** [comment]
````
[   INFO] <2023-08-28T06:58:29.401Z> [LanguageServer] Added FusionWorkspace p3b with path c:\Users\myUser\Desktop\Arbeitsordner\p3b
[VERBOSE] <2023-08-28T06:58:29.639Z> [LanguageServer] Configuration: {"folders":{"packages":["DistributionPackages","Packages/Application","Packages/Framework","Packages/Plugins","Packages/Sites","Packages/Neos","Packages/Carbon"],"workspaceAsPackageFallback":true,"fusion":["Resources/Private/Fusion","Resources/Private/FusionModule","Resources/Private/FusionModules","Resources/Private/FusionPlugins","NodeTypes"],"ignore":["Packages/Libraries"],"followSymbolicLinks":false,"includeHiddenDirectories":false},"diagnostics":{"enabled":true,"ignoreNodeTypes":["Neos.Neos:Plugin"],"levels":{"deprecations":"hint"},"ignore":{"folders":["Packages/"]},"alwaysDiagnoseChangedFile":false},"inlayHint":{"depth":"literal"},"extensions":{"modify":true},"code":{"deprecations":{"fusion":{"prototypes":{"Neos.Fusion:Array":"Neos.Fusion:Join","Neos.Fusion:Collection":"Neos.Fusion:Loop","Neos.Fusion:RawCollection":"Neos.Fusion:Map","Neos.Fusion:RawArray":"Neos.Fusion:DataStructure","Neos.Fusion:UriBuilder":"Neos.Fusion:ActionUri"}}},"actions":{"createNodeTypeConfiguration":{"template":"{nodeTypeName}:\n  properties:"}}},"logging":{"level":"debug","inspect":false}}
[  DEBUG] <2023-08-28T06:58:29.641Z> [FusionWorkspace|p3b] fallback to using workspace as package
[  ERROR] <2023-08-28T06:58:29.642Z> [NeosWorkspace|p3b] File not found! c:\Users\myUser\Desktop\Arbeitsordner\p3b
[  ERROR] <2023-08-28T06:58:29.643Z> [NeosWorkspace|p3b]     Error:  Error: ENOENT: no such file or directory, open 'c:\Users\myUser\Desktop\Arbeitsordner\p3b\composer.json'
    at Object.openSync (node:fs:596:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.readFileSync (node:fs:464:35)
    at t.readFileSync (node:electron/js2c/asar_bundle:2:9165)
    at new NeosPackage (c:\Users\myUser\.vscode\extensions\simonschmidt.vscode-neos-fusion-lsp-0.3.7\server\out\main.js:200:126)
    at ra.addPackage (c:\Users\myUser\.vscode\extensions\simonschmidt.vscode-neos-fusion-lsp-0.3.7\server\out\main.js:200:2731)
    at ua.init (c:\Users\myUser\.vscode\extensions\simonschmidt.vscode-neos-fusion-lsp-0.3.7\server\out\main.js:200:16608)
    at fa.onDidChangeConfiguration (c:\Users\myUser\.vscode\extensions\simonschmidt.vscode-neos-fusion-lsp-0.3.7\server\out\main.js:201:11770) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'c:\\Users\\myUser\\Desktop\\Arbeitsordner\\p3b\\composer.json'
}
[   INFO] <2023-08-28T06:58:29.648Z> [FusionWorkspace|p3b] Successfully parsed 0 fusion files. 
[  DEBUG] <2023-08-28T06:58:29.649Z> [FusionWorkspace|p3b] <35> Will diagnose 0 files
[  DEBUG] <2023-08-28T06:58:29.649Z> [FusionWorkspace|p3b] <35>...finished
[  DEBUG] <2023-08-28T06:58:29.756Z> [InlayHintLanguageFeature]  file:///c%3A/Users/MyUser/Desktop/Arbeitsordner/p3b/neos/DistributionPackages/Demo.Site/Resources/Private/Fusion/Content/HinweisListe.fusion
````

There really is no composer.json in the root folder of my workspace, it's one folder further down in my folder structure. If I open that folder, everything works fine. So a possible fix would be for the program to check sub-folders for the composer.json.

**Comment by sjsone** [comment]
Folder paths are configurable in the settings:

<img width="497" alt="Screenshot 2023-08-28 at 10 33 07" src="https://github.com/sjsone/vscode-neos-fusion-lsp/assets/87149727/aedca772-d046-48ac-ac58-cc92e0bc9493">

by looking at the logs you should just have to prefix every path with `neos`.

**Comment by Discostu36** [comment]
Ok, I see. I did it the other way round and moved everything up in the folder structure, and it works now. 

Maybe this could be made more idiot-proof. For example, the message in the log could say something like "Composer.json not found. Please make sure that the root folder of your workspace is the root /neos folder, or update the folder paths in the plugin settings accordingly". The current message is misleading, as it sounds like the plugin doesn't find / can't access the workspace folder.

**Comment by sjsone** [comment]
Glad it works now! 

I have already planned something like a new `Neos Workspace Root` (naming TBD) setting which acts as a prefix to the paths. This will enable a few things: 

1. it can be extended to an array which implies multi-workspace capability (so multiple neos installations and/or packages in one folder) 
2. an Error-Message can link directly to the setting which has some examples etc. or even have an input field directly in the notification to quick-set the prefix
3. it should be possible to "self-heal" the configuration and provide at least some suggestions for the field or even set the prefix and just inform the user about the change

Feedback and help are greatly appreciated so if you want to help, just make a PR 🚀 😁
