### ISSUE TITLE
Filtering by PHP Class instances shows error

### ISSUE THREAD

**Issue by Benjamin-K** [sjsone/vscode-neos-fusion-lsp#8]
If you have an Eel-Helper, that will give you an array of PHP class instances, a deprecation warning will be shown.

<img width="552" alt="image" src="https://github.com/sjsone/vscode-neos-fusion-lsp/assets/3098031/fd869332-00e5-4cff-b37c-abe282b507f5">

When filtering by an instanceof a PHP class (with a beginning backslash `\`), the deprecation warning should not be shown, as this is a valid use case.

**Comment by sjsone** [comment]
Yea thats a complete oversight of mine. Thanks for the report!

**Comment by sjsone** [comment]
The fix is now live as pre-release 0.3.7
