### ISSUE TITLE
FEATURE: Full autocompletion inside NodeTypes

### ISSUE THREAD

**Issue by crydotsnake** [sjsone/vscode-neos-fusion-lsp#9]
It would be awesome to have Full autocompletion for the supported keywords/properties in the YAML NodeTypes. For example if i write something like: `ui.label`.

**Comment by sjsone** [comment]
You can already achieve this with the [YAML Extension by RedHat](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml) and this schema configuration (provided by @Sebobo):

```json
    "yaml.schemas": {
    
        "https://raw.githubusercontent.com/Sebobo/Shel.Neos.Schema/main/NodeTypes.Schema.json": [
            "DistributionPackages/*/Configuration/NodeTypes*.yaml",
            "DistributionPackages/*/NodeTypes/**/*.yaml"
        ],
        "https://raw.githubusercontent.com/Sebobo/Shel.Neos.Schema/main/NodeMigration.Schema.json": "DistributionPackages/*/Migrations/ContentRepository/Version*.yaml",
        "https://raw.githubusercontent.com/Sebobo/Shel.Neos.Schema/main/Caches.Schema.json": "DistributionPackages/*/Configuration/Caches*.yaml",
        "https://raw.githubusercontent.com/Sebobo/Shel.Neos.Schema/main/Routes.Schema.json": "DistributionPackages/*/Configuration/Routes*.yaml"
    },
```

There are definitely plans in the future to add this YAML Extension to the auto-configuration-feature. 

That will probably happen when there is a NEOS-Extension-Pack for VSCode (like there are [ones for Node.js for example](https://marketplace.visualstudio.com/items?itemName=waderyan.nodejs-extension-pack)).

**Comment by crydotsnake** [comment]
Thanks for the hint!

I've addded the Schema configuration to my `settings.json` but it still doesent work.

**Comment by crydotsnake** [comment]
Thanks for the hint!

Got it working :)
